---
engines:
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "src/**/*.coffee"
  - "src/**/*.scss"
exclude_paths:
- dist/
- Gruntfile.coffee
- README.md
- bower.json
- coffeelint.json
- package.json
