// Generated by CoffeeScript 1.7.1
var mkmobileApp;

mkmobileApp = angular.module('mkmobileApp', ['ngRoute', 'mkmobileControllers', 'mkmobileFilters', 'mkmobileServices']);

mkmobileApp.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/search', {
      templateUrl: 'partials/search.html',
      controller: 'SearchCtrl',
      reloadOnSearch: false
    }).when('/products/:productId', {
      templateUrl: 'partials/product.html',
      controller: 'ProductCtrl'
    }).otherwise({
      redirectTo: '/search'
    });
  }
]);

mkmobileApp.config([
  '$httpProvider', function($httpProvider) {
    return $httpProvider.interceptors.push([
      '$q', function($q) {
        var uniqueRequests;
        uniqueRequests = {};
        return {
          request: function(config) {
            var _ref;
            if (config.unique) {
              if ((_ref = uniqueRequests[config.unique]) != null) {
                _ref.resolve();
              }
              uniqueRequests[config.unique] = $q.defer();
              config.timeout = uniqueRequests[config.unique].promise;
            }
            return config || $q.when(config);
          }
        };
      }
    ]);
  }
]);

//# sourceMappingURL=app.map
