// Generated by CoffeeScript 1.7.1
var mkmobileApp;

mkmobileApp = angular.module('mkmobileApp', ['ngRoute', 'ngAnimate', 'mkmobileControllers', 'mkmobileFilters', 'mkmobileServices', 'mkmobileDirectives']);

mkmobileApp.config([
  '$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
    $locationProvider.html5Mode(true);
    return $routeProvider.when('/login/:search?', {
      "class": 'login',
      templateUrl: '/partials/login.html',
      controller: 'SearchCtrl'
    }).when('/product/:productId', {
      "class": 'product',
      templateUrl: '/partials/product.html',
      controller: 'ProductCtrl'
    }).otherwise({
      redirectTo: '/login'
    });
  }
]);

mkmobileApp.config([
  '$httpProvider', function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    $httpProvider.defaults.cache = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
    return $httpProvider.interceptors.push([
      '$q', function($q) {
        var uniqueRequests;
        uniqueRequests = {};
        return {
          request: function(config) {
            var _ref;
            if (config.unique) {
              if ((_ref = uniqueRequests[config.unique]) != null) {
                _ref.resolve();
              }
              uniqueRequests[config.unique] = $q.defer();
              config.timeout = uniqueRequests[config.unique].promise;
            }
            return config || $q.when(config);
          }
        };
      }
    ]);
  }
]);

mkmobileApp.run([
  '$rootScope', function($rootScope) {
    return $rootScope.$on('$routeChangeSuccess', function(event, current, previous) {
      return $rootScope.viewClass = current.$$route["class"];
    });
  }
]);

//# sourceMappingURL=app.map
