// Generated by CoffeeScript 1.7.1
var mkmobileControllers;

mkmobileControllers = angular.module('mkmobileControllers', []);

mkmobileControllers.controller('SearchCtrl', [
  '$scope', '$routeParams', '$location', 'MkmApi', function($scope, $routeParams, $location, MkmApi) {
    $scope.search = function() {
      return $scope.data = MkmApi.search($scope.query);
    };
    $scope.updateHistory = function() {
      return $location.search({
        search: $scope.query
      });
    };
    $scope.query = $routeParams.search;
    $scope.search();
    $scope.sort = "name";
    $scope.loadResults = function() {
      if ($scope.data.products.length >= $scope.data.count || $scope.data.loading) {
        return;
      }
      return MkmApi.search($scope.query, $scope.data);
    };
    return $scope.login = function() {
      console.log("logging in");
      return MkmApi.login();
    };
  }
]);

mkmobileControllers.controller('ProductCtrl', [
  '$scope', '$routeParams', 'MkmApi', function($scope, $routeParams, MkmApi) {
    $scope.productData = MkmApi.product($routeParams.productId);
    $scope.data = MkmApi.articles($routeParams.productId);
    $scope.loadArticles = function() {
      if ($scope.data.articles.length >= $scope.data.count || $scope.data.loading) {
        return;
      }
      return MkmApi.articles($routeParams.productId, $scope.data);
    };
    return $scope.addToCart = function(article) {
      if (!MkmApi.isLoggedIn()) {
        return;
      }
      console.log("add", article.idArticle);
      return article.count--;
    };
  }
]);

//# sourceMappingURL=controllers.map
