// Generated by CoffeeScript 1.7.1
var mkmobileDirectives;

mkmobileDirectives = angular.module('mkmobileDirectives', []);

mkmobileDirectives.directive('whenScrolled', function() {
  return {
    link: function(scope, elm, attr) {
      var raw;
      raw = elm[0];
      return elm.bind('scroll', function() {
        if (raw.scrollTop + raw.offsetHeight >= raw.scrollHeight) {
          return scope.$apply(attr.whenScrolled);
        }
      });
    }
  };
});

//# sourceMappingURL=directives.map
