// Generated by CoffeeScript 1.7.1
var mkmobileServices;

mkmobileServices = angular.module('mkmobileServices', ['ngResource']);

mkmobileServices.factory('MkmApi', [
  '$resource', function($resource) {
    var apiURL;
    apiURL = '/api';
    return $resource(apiURL + '/:type/:param1/:param2/:param3/:param4/:param5', {}, {
      search: {
        method: 'GET',
        params: {
          type: "products",
          param2: "1",
          param3: "1",
          param4: "false"
        },
        unique: "search"
      },
      articles: {
        method: 'GET',
        params: {
          type: "articles"
        },
        cache: false
      },
      product: {
        method: 'GET',
        params: {
          type: "product"
        }
      }
    });
  }
]);

mkmobileServices.factory('DataCache', [
  '$cacheFactory', function($cacheFactory) {
    var cache;
    cache = {
      product: $cacheFactory('products', {
        capacity: 500
      })
    };
    return {
      product: function(id, data) {
        if (data != null) {
          cache.product.put(id, data);
        }
        if (id != null) {
          return cache.product.get(id);
        }
      }
    };
  }
]);

//# sourceMappingURL=services.map
