// Generated by CoffeeScript 1.7.1
var mkmobileServices;

mkmobileServices = angular.module('mkmobileServices', ['ngResource']);

mkmobileServices.factory('MkmApi', [
  '$resource', '$q', function($resource, $q) {
    return $resource('/api.php', {}, {
      search: {
        method: 'GET',
        params: {
          search: ""
        },
        cache: true,
        unique: true
      },
      articles: {
        method: 'GET',
        params: {
          articles: ""
        },
        cache: true
      }
    });
  }
]);

//# sourceMappingURL=services.map
